FROM openjdk:8-jdk-alpine
ARG JAR_FILE=target/*.jar
copy ./target/uploadPhotoService-0.0.1-SNAPSHOT.jar uploadPhotoService-0.0.1-SNAPSHOT.jar
CMD ["java","-jar","uploadPhotoService-0.0.1-SNAPSHOT.jar"]
RUN chmod 777 uploadPhotoService-0.0.1-SNAPSHOT.jar ENTRYPOINT ["java", "-jar", "/app.jar"]
ENTRYPOINT ["java", "-jar", "/app.jar"]
